baseURL = "https://kobecoleman.netlify.app"
title = "Kobe Coleman"
theme = "Toha"

# Theme configuration
[params]
env = "production"
author = "Kobe Coleman"
description = "Everything about Kobe Coleman"
keywords = ["Blog", "Portfolio", "Toha"]
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableScrollToTop = false

[params.label]
text = "Home"
icon = "/profile.png"
iconHeight = 24

[params.profileMode]
enabled = true
title = "Kobe Coleman"
subtitle = "Software Developer, Musician, and Chess Player"
imageUrl = "ProKobe.jpg"
imageWidth = 120
imageHeight = 120

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/kobe-coleman-344286187/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ColemanKobe"

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "link"
name = "A link"
url = "https://google.com/search?tbm=isch&q=cute%20puppies"
weight = 30
